<tr class="setting-communitylist" id="CommunityID_<?php echo $wo['communitylist']['id']?>" data-group-id="<?php echo $wo['communitylist']['id']?>" data_selected="<?php echo $wo['communitylist']['id']?>">
   <td><input type="checkbox" id="check-data-<?php echo $wo['communitylist']['id']?>" class="delete-checkbox filled-in"><label for="check-data-<?php echo $wo['communitylist']['id']?>"></label></td>
   <td><?php echo $wo['communitylist']['id']?></td>
   <td>
      <a href="<?php echo $wo['communitylist']['url']; ?>">
      <img src="<?php echo $wo['communitylist']['avatar']; ?>" class="setting-avatar" alt="<?php echo $wo['communitylist']['avatar']?> Page Picture">
      <?php echo $wo['communitylist']['community_name']; ?>
      </a>
   </td>
   <td><?php echo $wo['communitylist']['category'];?></td>
   <td><?php echo $wo['communitylist']['members'];?></td>
   <td>
      <a target = "_blank" class="btn bg-info admn_table_btn" href="<?php echo Wo_SeoLink('index.php?link1=community-setting&community=' . $wo['communitylist']['community_name']) ?>">Edit</a>
      <button onclick="Wo_DeleteCommunity(<?php echo $wo['communitylist']['id']?>,'hide');" type="button" class="btn bg-danger admn_table_btn">Delete</button>
   </td>
</tr>