<div class="col-xs-6">
	<div class="wow_content wow_my_groups">
		<div class="avatar">
			<a href="<?php echo $wo['CommunityList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['CommunityList']['username']?>">
				<img src="<?php echo $wo['CommunityList']['avatar'];?>" alt="<?php echo $wo['CommunityList']['name']; ?> Profile Picture" />
			</a>
		</div>
		<div class="wow_my_groups_info">
			<h3 class="page_title"><a href="<?php echo $wo['CommunityList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['CommunityList']['username']?>"><?php echo $wo['CommunityList']['name']; ?></a></h3>
			<p><?php echo Wo_CountCommunityMembers($wo['CommunityList']['id']);?> <?php echo $wo['lang']['members'];?></p>
			<?php echo Wo_GetCommunityJoinButton($wo['CommunityList']['id']);?>
		</div>
	</div>
</div>