<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 profile-lists singlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr big_size">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path></svg></span> <?php echo $wo['lang']['communities']; ?>
					</div>
				</div>
			</div>
			<div class="page-margin wow_content">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_menu">
						<ul class="list-unstyled">
						<?php if(Wo_IsAdmin() || Wo_IsModerator()) { ?>
							<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=communities'); ?>" data-ajax="?link1=communities"><?php echo $wo['lang']['all_communities'] ?></a></li>
						<?php } ?>
							<li><a href="<?php echo Wo_SeoLink('index.php?link1=joined-communities'); ?>" data-ajax="?link1=joined-communities"><?php echo $wo['lang']['joined_communities'] ?></a></li>
							<li><a href="<?php echo Wo_SeoLink('index.php?link1=suggested-communities'); ?>" data-ajax="?link1=suggested-communities"><?php echo $wo['lang']['suggested_communities'] ?></a></li>
						</ul>
						<?php if(Wo_IsAdmin() || Wo_IsModerator()) { ?>
							<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=create-community');?>" data-ajax="?link1=create-community"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['create'] ?></a>
						<?php } else { ?>
							<a class="btn btn-main btn-mat btn-mat-raised" href="<?php echo Wo_SeoLink('index.php?link1=request-community');?>" data-ajax="?link1=request-community"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z"></path></svg> <?php echo $wo['lang']['Request Community'] ?></a>
						<?php } ?>
					</div>
				</div>
			</div>
			<div class="row">
				<?php
					$pages = Wo_GetMyCommunities();
					if (!is_array($pages)) {
						$pages = array();
					}
					if (!empty($pages)) {
						foreach ($pages as $wo['community']) {
							echo Wo_LoadPage('community/community-list');
						}
					} else {
						echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path></svg>' . $wo['lang']['no_communities_found'] . '</div>';
					}
				?>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<!-- .row -->
</div>