<div class="col-xs-6 col-sm-4 nearby_user_wrapper text-center user-data" data-page-id="<?php echo $wo['CommunityList']['id'];?>">
  <a href="<?php echo $wo['CommunityList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['CommunityList']['username']?>">
    <div class="avatar">
      <img src="<?php echo $wo['CommunityList']['avatar'];?>" alt="<?php echo $wo['CommunityList']['name']; ?> Profile Picture" />
    </div>
    <span class="user_wrapper_link"><?php echo $wo['CommunityList']['name']; ?></span>
  </a>
  <div class="user-lastseen">
    <?php echo $wo['lang']['members'];?>: <?php echo Wo_CountCommunityMembers($wo['CommunityList']['id']); ?>
  </div>
  <div class="user-follow-button">
    <?php echo Wo_GetCommunityJoinButton($wo['CommunityList']['id']);?>
  </div>
</div>