<div class="container-fluid">
    <div>
        <h3>Create New Community</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Manage Features</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Communities</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Create New Community</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Create New Community</h6>
                    <div class="alert alert-info">Create a community or subcommunity.</div>
                    <div class="newforum-alert"></div>
                    <div class="newforum-error-alert"></div>
                    <form class="newforum" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Name</label>
                                <input type="text" id="name" name="name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <label for="community_name" class="form-label"><?php echo $wo['lang']['community'];?> URL</label>
                            <div class="input-group">
                                <span class="input-group-addon"><?php echo $wo['config']['site_url'];?>/</span>
                                <input id="group_name" name="community_name" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Description</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="wow_form_fields">
                                    <label for="privacy"><?php echo $wo['lang']['group_type']; ?></label>
                                    <select class="form-control show-tick" id="privacy" name="privacy">
                                        <option value="1" ><?php echo $wo['lang']['public'];?> </option>
                                        <option value="2" ><?php echo $wo['lang']['private'];?> </option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="wow_form_fields">
                                    <label for="category"><?php echo $wo['lang']['category']; ?></label>
                                    <select class="form-control show-tick" name="category" id="category" onchange="GetGroupSubCategory(this)">
                                        <?php foreach ($wo['group_categories'] as $category_id => $category_name) {?>
                                        <option value="<?php echo $category_id?>"><?php echo $category_name; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                            <?php if (!empty($wo['community_sub_categories'])) { ?>
                            <div class="col-md-6">
                                <div class="wow_form_fields">
                                    <label class="form-label" for="community_sub_category"><?php echo $wo['lang']['sub_category']; ?></label>
                                    <select class="form-control show-tick" name="community_sub_category" id="community_sub_category">
                                        <?php
                                        if (!empty($wo['community_sub_categories'][array_keys($wo['community_categories'])[0]])) {
                                        foreach ($wo['community_sub_categories'][array_keys($wo['community_categories'])[0]] as $id => $sub_category) { ?>
                                            <option value="<?php echo $sub_category['id']?>"><?php echo $sub_category['lang']; ?></option>
                                        <?php } } ?>
                                    </select>
                                </div>
                            </div>
                            <?php } ?>
                            <div class="clear"></div>
                            <?php $fields = Wo_GetCustomFields('community'); 
                            if (!empty($fields)) {
                                foreach ($fields as $key => $wo['field']) {
                                    echo Wo_LoadPage('community/fields');
                                }
                            }
                            ?>
                        </div>
                        <label class="form-label" for="section">Parent Community</label>
                        <select class="form-control show-tick" id="section" name="section">
                          <?php foreach (Wo_GetForumSec(array('forums'=>false,'limit'=>500)) as $section): ?>
							<option value="<?php echo $section['id']; ?>">
								<?php echo $section['section_name']; ?>
							</option>
						<?php endforeach ?>
                        </select>
                        <div class="clearfix"></div>
                        <br><br>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Create Community</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    var form_new_forum = $('form.newforum');
    form_new_forum.ajaxForm({
        url: Wo_Ajax_Requests_File()  +  '?f=add-new-forum&hash=' + $('.main_session').val(),
        beforeSend: function() {
            form_new_forum.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.newforum-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> New community created successfully.</div>');
                setTimeout(function () {
                    $('.newforum-alert').empty();
                }, 2000);
            } else {
                $('.newforum-alert').html('<div class="alert alert-danger">'+data['message']+'</div>');
                setTimeout(function () {
                    $('.newforum-alert').empty();
                }, 2000);
            } 
            form_new_forum.find('.waves-effect').text('Create Forum');
        }
    });
});
</script>